# -*- coding: utf-8 -*-
"""2548527_dl_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSaG0G_df9H5RsLvdFiuxKPLhDvAhNtz
"""

import pandas as pd
import numpy as np

import tensorflow as tf

import torch
import torch.nn as nn
import torch.optim as optim

df = pd.DataFrame({
    'X1': [0, 0, 1, 1],
    'X2': [0, 1, 0, 1],
    'Y': [0, 1, 1, 0]
})

df



# Convert DataFrame to NumPy arrays
X = df[['X1', 'X2']].values.astype(np.float32)
y = df[['Y']].values.astype(np.float32)

# Hyperparameters
learning_rate = 0.01
epochs = 1000
check_epochs = [100, 300, 500, 700, 1000]

# Global dictionary to store results for all frameworks
results = {
    "TensorFlow": {},
    "Keras": {},
    "PyTorch": {}
}

# Initialize weights and biases
W1 = tf.Variable(tf.random.normal([2, 2]))
b1 = tf.Variable(tf.zeros([2]))

W2 = tf.Variable(tf.random.normal([2, 1]))
b2 = tf.Variable(tf.zeros([1]))

# Optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

# Training loop
for epoch in range(1, epochs + 1):
    with tf.GradientTape() as tape:
        hidden = tf.nn.relu(tf.matmul(X, W1) + b1)
        output = tf.sigmoid(tf.matmul(hidden, W2) + b2)

        loss = tf.keras.losses.binary_crossentropy(y, output)
        loss = tf.reduce_mean(loss)

    gradients = tape.gradient(loss, [W1, b1, W2, b2])
    optimizer.apply_gradients(zip(gradients, [W1, b1, W2, b2]))

    if epoch in check_epochs:
        results["TensorFlow"][epoch] = float(loss.numpy())

# Build Keras model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile model
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy'
)

# Custom callback to store loss at specific epochs
class LossLogger(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        epoch_num = epoch + 1
        if epoch_num in check_epochs:
            results["Keras"][epoch_num] = logs["loss"]

# Train model
model.fit(
    X, y,
    epochs=epochs,
    verbose=0,
    callbacks=[LossLogger()]
)

# Convert NumPy arrays to PyTorch tensors
X_torch = torch.tensor(X)
y_torch = torch.tensor(y)

# Define MLP model
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(2, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x

model = MLP()

# Loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(1, epochs + 1):
    optimizer.zero_grad()

    outputs = model(X_torch)
    loss = criterion(outputs, y_torch)

    loss.backward()
    optimizer.step()

    if epoch in check_epochs:
        results["PyTorch"][epoch] = loss.item()

import pandas as pd

# Create comparison table
comparison_df = pd.DataFrame({
    "Epoch": check_epochs,
    "TensorFlow Loss": [results["TensorFlow"][e] for e in check_epochs],
    "Keras Loss": [results["Keras"][e] for e in check_epochs],
    "PyTorch Loss": [results["PyTorch"][e] for e in check_epochs]
})

# Print table
print(comparison_df.to_string(index=False))

import matplotlib.pyplot as plt

# Epochs to plot
epochs_plot = check_epochs

# Extract loss values
tf_losses = [results["TensorFlow"][e] for e in epochs_plot]
keras_losses = [results["Keras"][e] for e in epochs_plot]
pytorch_losses = [results["PyTorch"][e] for e in epochs_plot]

# Plot loss curves
plt.figure()
plt.plot(epochs_plot, tf_losses, marker='o', label="TensorFlow (Low-level)")
plt.plot(epochs_plot, keras_losses, marker='o', label="Keras")
plt.plot(epochs_plot, pytorch_losses, marker='o', label="PyTorch")

plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss Comparison Across Frameworks (XOR MLP)")
plt.legend()
plt.show()

