# -*- coding: utf-8 -*-
"""2548527_lab_4.2_dl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PFjq7BXpSKZnQnUyZxJibijGX4961fk
"""

import os, yaml, torch, numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from pathlib import Path
from PIL import Image

!pip install ultralytics -q

from ultralytics import YOLO

from google.colab import drive
drive.mount('/content/drive')


import zipfile, os

zip_path = "/content/drive/MyDrive/brain-tumor.zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall("/content/")

print("Train:", len(os.listdir("/content/brain-tumor/images/train")))
print("Val:  ", len(os.listdir("/content/brain-tumor/images/val")))

!python train.py \
  --img 416 \
  --batch 16 \
  --epochs 20 \
  --data /content/brain_tumor_small.yaml \
  --weights yolov5s.pt \
  --name yolov5_brain_small \
  --workers 2

# Yaml fix
with open(YAML_PATH, "w") as f:
    yaml.dump({
        "path":  DATASET_PATH,
        "train": "images/train",
        "val":   "images/val",
        "names": {0: "negative", 1: "positive"}
    }, f, default_flow_style=False)
print("✅ YAML ready")

# YOLOv8 (pretrained)

model_v8 = YOLO("yolov8n.pt")

model_v8.train(
    data     = YAML_PATH,
    epochs   = EPOCHS,
    imgsz    = IMG_SIZE,
    batch    = BATCH,
    device   = DEVICE,
    name     = "v8",
    project  = "results",
    exist_ok = True,
    freeze   = 10,
    optimizer= "Adam",
    lr0      = 0.001,
    verbose  = False
)
print("✅ YOLOv8 done!")

# TRAIN YOLOv5 (pretrained)

model_v5 = YOLO("yolov5nu.pt")  # nano = fastest, pretrained on COCO

model_v5.train(
    data     = YAML_PATH,
    epochs   = EPOCHS,
    imgsz    = IMG_SIZE,
    batch    = BATCH,
    device   = DEVICE,
    name     = "v5",
    project  = "results",
    exist_ok = True,
    freeze   = 10,
    optimizer= "Adam",
    lr0      = 0.001,
    verbose  = False
)
print("✅ YOLOv5 done!")

import os

# Search entire colab filesystem for best.pt
print("Searching for best.pt...")
for root, dirs, files in os.walk("/"):
    for file in files:
        if file == "best.pt":
            print(os.path.join(root, file))

from ultralytics import YOLO

v5 = YOLO("/content/yolov5/runs/train/yolov5_brain_small/weights/best.pt")
v8 = YOLO("/content/runs/detect/yolov8_brain_small/weights/best.pt")

# ENSEMBLE FUNCTION
# ─────────────────────────────────────────
def compute_iou(box, boxes):
    x1 = np.maximum(box[0], boxes[:, 0])
    y1 = np.maximum(box[1], boxes[:, 1])
    x2 = np.minimum(box[2], boxes[:, 2])
    y2 = np.minimum(box[3], boxes[:, 3])
    inter = np.maximum(0, x2-x1) * np.maximum(0, y2-y1)
    area1 = (box[2]-box[0]) * (box[3]-box[1])
    area2 = (boxes[:,2]-boxes[:,0]) * (boxes[:,3]-boxes[:,1])
    return inter / (area1 + area2 - inter + 1e-6)

def ensemble_predict(img_path, m1, m2, conf=0.25, iou_thresh=0.5):
    r1 = m1.predict(img_path, conf=conf, verbose=False)[0]
    r2 = m2.predict(img_path, conf=conf, verbose=False)[0]

    all_boxes, all_conf, all_cls = [], [], []
    for r in [r1, r2]:
        if r.boxes and len(r.boxes):
            all_boxes.append(r.boxes.xyxy.cpu().numpy())
            all_conf.append(r.boxes.conf.cpu().numpy())
            all_cls.append(r.boxes.cls.cpu().numpy())

    if not all_boxes:
        return np.array([]), np.array([]), np.array([])

    boxes = np.vstack(all_boxes)
    confs = np.concatenate(all_conf)
    classes = np.concatenate(all_cls)

    # NMS
    order = np.argsort(confs)[::-1]
    boxes, confs, classes = boxes[order], confs[order], classes[order]
    keep = []
    suppressed = np.zeros(len(boxes), dtype=bool)
    for i in range(len(boxes)):
        if not suppressed[i]:
            keep.append(i)
            if i+1 < len(boxes):
                ious = compute_iou(boxes[i], boxes[i+1:])
                suppressed[i+1:] |= ious > iou_thresh

    idx = np.array(keep)
    return boxes[idx], confs[idx], classes[idx]

# v5 vs v8 vs Ensemble

NAMES  = {0: "Negative", 1: "Positive"}
COLORS = {0: "green",    1: "red"}

def visualize(img_path, v5, v8):
    img = np.array(Image.open(img_path).convert("RGB"))
    r5  = v5.predict(img_path, conf=0.25, verbose=False)[0]
    r8  = v8.predict(img_path, conf=0.25, verbose=False)[0]
    eb, ec, el = ensemble_predict(img_path, v5, v8)

    fig, axes = plt.subplots(1, 4, figsize=(20, 4))
    titles = ["Original", "YOLOv5", "YOLOv8", "Ensemble"]
    results = [None, r5, r8, (eb, ec, el)]

    for ax, title, res in zip(axes, titles, results):
        ax.imshow(img); ax.axis("off"); ax.set_title(title, fontsize=11)
        if res is None: continue
        if isinstance(res, tuple):
            boxes, confs, cls_arr = res
        else:
            if not res.boxes or len(res.boxes) == 0: continue
            boxes = res.boxes.xyxy.cpu().numpy()
            confs = res.boxes.conf.cpu().numpy()
            cls_arr = res.boxes.cls.cpu().numpy()
        for box, conf, c in zip(boxes, confs, cls_arr):
            c = int(c)
            x1,y1,x2,y2 = box
            rect = patches.Rectangle((x1,y1), x2-x1, y2-y1,
                                      linewidth=2, edgecolor=COLORS[c], facecolor='none')
            ax.add_patch(rect)
            ax.text(x1, y1-5, f"{NAMES[c]} {conf:.2f}",
                    color=COLORS[c], fontsize=8, fontweight='bold',
                    bbox=dict(facecolor='white', alpha=0.5, pad=1))

    plt.tight_layout()
    out = f"pred_{Path(img_path).stem}.png"
    plt.savefig(out, dpi=120, bbox_inches="tight")
    plt.show()


val_imgs = list(Path(f"{DATASET_PATH}/images/val").glob("*.jpg"))[:5]
for img in val_imgs:
    visualize(str(img), best_v5, best_v8)

