# -*- coding: utf-8 -*-
"""2548527_lab4.1_dl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KSuJcpvSewC3_N_zFnPt3uBtLEFSwkZ
"""

pip install numpy opencv-python matplotlib

import numpy as np
import cv2
import os
import matplotlib.pyplot as plt

import json
import os

kaggle_dict = {
    "username": "jouavp",
    "key": "KGAT_3704facdfe8053884b591cc1a4be55c7"
}

os.makedirs("/root/.kaggle", exist_ok=True)

with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump(kaggle_dict, f)

!chmod 600 /root/.kaggle/kaggle.json

!pip install -q kaggle

!kaggle datasets list

!kaggle datasets download -d puneet6060/intel-image-classification

!unzip -q intel-image-classification.zip

import os
print(os.listdir("/content/seg_train/seg_train"))

IMG_SIZE = 64
TRAIN_PER_CLASS = 300
CLASSES = ['buildings','forest','glacier','mountain','sea','street']
NUM_CLASSES = len(CLASSES)
EPOCHS = 3
LR = 0.001

DATA_PATH = "/content/seg_train/seg_train"

# -----------------------------
# LOAD DATASET
# -----------------------------
def load_data(path):

    X_train, y_train = [], []
    X_test, y_test = [], []

    for label, cls in enumerate(CLASSES):

        folder = os.path.join(path, cls)
        images = os.listdir(folder)

        for i, img_name in enumerate(images):

            img_path = os.path.join(folder, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0

            if i < TRAIN_PER_CLASS:
                X_train.append(img)
                y_train.append(label)
            else:
                X_test.append(img)
                y_test.append(label)

    return (np.array(X_train), np.array(y_train),
            np.array(X_test), np.array(y_test))


print("Loading dataset...")
X_train, y_train, X_test, y_test = load_data(DATA_PATH)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

# -----------------------------
# CONVOLUTION LAYER
# -----------------------------
class ConvLayer:

    def __init__(self, num_filters=8):
        self.filters = np.random.randn(num_filters,3,3,3) * 0.1

    def forward(self, image):

        h,w,_ = image.shape
        num_filters = self.filters.shape[0]

        output = np.zeros((h-2,w-2,num_filters))

        for f in range(num_filters):
            filt = self.filters[f]

            for i in range(h-2):
                for j in range(w-2):
                    region = image[i:i+3, j:j+3]
                    output[i,j,f] = np.sum(region * filt)

        return output

# -----------------------------
# MAXPOOL
# -----------------------------
class MaxPool:

    def forward(self, x):
        h,w,f = x.shape
        output = np.zeros((h//2,w//2,f))

        for i in range(0,h,2):
            for j in range(0,w,2):
                region = x[i:i+2, j:j+2]
                output[i//2,j//2] = np.max(region,axis=(0,1))

        return output

# -----------------------------
# ACTIVATIONS
# -----------------------------
def relu(x):
    return np.maximum(0,x)

def softmax(x):
    exp = np.exp(x - np.max(x))
    return exp / np.sum(exp)

# -----------------------------
# MODEL
# -----------------------------
conv = ConvLayer(8)
pool = MaxPool()

# compute flattened size automatically
sample = pool.forward(relu(conv.forward(X_train[0])))
FLAT_SIZE = sample.flatten().shape[0]

W = np.random.randn(FLAT_SIZE, NUM_CLASSES) * 0.01
b = np.zeros(NUM_CLASSES)

# -----------------------------
# FORWARD PASS
# -----------------------------
def forward(image):

    x = conv.forward(image)
    x = relu(x)
    x = pool.forward(x)

    x = x.flatten()

    logits = np.dot(x, W) + b
    probs = softmax(logits)

    return probs, x

# -----------------------------
# LOSS
# -----------------------------
def cross_entropy(pred, label):
    return -np.log(pred[label] + 1e-9)

# -----------------------------
# TRAINING
# -----------------------------
loss_history = []
acc_history = []

for epoch in range(EPOCHS):

    total_loss = 0
    correct = 0

    for img, label in zip(X_train, y_train):

        probs, features = forward(img)

        loss = cross_entropy(probs, label)
        total_loss += loss

        pred_class = np.argmax(probs)
        if pred_class == label:
            correct += 1

        # -------- BACKPROP (FC layer) --------
        grad = probs
        grad[label] -= 1

        global W, b
        W -= LR * np.outer(features, grad)
        b -= LR * grad

    epoch_loss = total_loss / len(X_train)
    epoch_acc = correct / len(X_train)

    loss_history.append(epoch_loss)
    acc_history.append(epoch_acc)

    print(f"Epoch {epoch+1}: Loss={epoch_loss:.4f}, Acc={epoch_acc:.4f}")

correct = 0

for img, label in zip(X_test, y_test):
    probs,_ = forward(img)
    if np.argmax(probs) == label:
        correct += 1

test_acc = correct / len(X_test)
print("\nTest Accuracy:", test_acc)

plt.figure(figsize=(7,5))
plt.plot(loss_history)
plt.title("Loss vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid()
plt.show()

plt.figure(figsize=(7,5))
plt.plot(acc_history)
plt.title("Accuracy vs Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid()
plt.show()



