# -*- coding: utf-8 -*-
"""Dl3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGZ5RM8wNL7dOAKURgw-iEAMvuR-Ochj
"""

import torch
import torch.nn as nn
import torch.optim as optim

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load dataset
data = load_breast_cancer()

X = data.data
y = data.target

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train = torch.tensor(X_train, dtype=torch.float32)
X_val = torch.tensor(X_val, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_val = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

print("Training samples:", X_train.shape)
print("Validation samples:", X_val.shape)

class LogisticModel(nn.Module):
    def __init__(self, input_dim):
        super(LogisticModel, self).__init__()
        self.linear = nn.Linear(input_dim, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

def train_model(model, optimizer, criterion, X_train, y_train, X_val, y_val, epochs=100):
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        # Training
        model.train()
        optimizer.zero_grad()

        y_pred = model(X_train)
        train_loss = criterion(y_pred, y_train)
        train_loss.backward()
        optimizer.step()

        # Validation
        model.eval()
        with torch.no_grad():
            y_val_pred = model(X_val)
            val_loss = criterion(y_val_pred, y_val)

        train_losses.append(train_loss.item())
        val_losses.append(val_loss.item())

    return train_losses, val_losses

def compute_accuracy(model, X, y):
    model.eval()
    with torch.no_grad():
        preds = model(X)
        preds = (preds >= 0.5).float()
    return accuracy_score(y.cpu(), preds.cpu())

input_dim = X_train.shape[1]

baseline_model = LogisticModel(input_dim)
criterion = nn.BCELoss()

optimizer = optim.SGD(baseline_model.parameters(), lr=0.01)

baseline_train_losses, baseline_val_losses = train_model(
    baseline_model, optimizer, criterion,
    X_train, y_train, X_val, y_val,
    epochs=100
)

plt.figure()
plt.plot(baseline_train_losses, label="Training Loss")
plt.plot(baseline_val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Baseline Model: Training vs Validation Loss")
plt.legend()
plt.show()

baseline_train_acc = compute_accuracy(baseline_model, X_train, y_train)
baseline_val_acc = compute_accuracy(baseline_model, X_val, y_val)

print("Baseline Training Accuracy:", baseline_train_acc)
print("Baseline Validation Accuracy:", baseline_val_acc)

weights = baseline_model.linear.weight.detach().cpu().numpy().flatten()

plt.figure()
plt.hist(weights, bins=30)
plt.xlabel("Weight Value")
plt.ylabel("Frequency")
plt.title("Baseline Model Weight Distribution")
plt.show()

weight_magnitude_baseline = np.mean(np.abs(weights))
weight_sparsity_baseline = np.sum(weights == 0) / weights.size

print("Baseline Weight Magnitude:", weight_magnitude_baseline)
print("Baseline Weight Sparsity:", weight_sparsity_baseline)

"""l1

"""

def l1_loss(model, lambda_l1):
    l1_penalty = 0.0
    for param in model.parameters():
        l1_penalty += torch.sum(torch.abs(param))
    return lambda_l1 * l1_penalty

def train_model_l1(model, optimizer, criterion, X_train, y_train, X_val, y_val, lambda_l1, epochs=100):
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        y_pred = model(X_train)
        loss = criterion(y_pred, y_train)
        cost = loss + l1_loss(model, lambda_l1)

        cost.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            y_val_pred = model(X_val)
            val_loss = criterion(y_val_pred, y_val)

        train_losses.append(cost.item())
        val_losses.append(val_loss.item())

    return train_losses, val_losses

lambda_l1 = 0.01

l1_model = LogisticModel(input_dim)
optimizer_l1 = optim.SGD(l1_model.parameters(), lr=0.01)

l1_train_losses, l1_val_losses = train_model_l1(
    l1_model, optimizer_l1, criterion,
    X_train, y_train, X_val, y_val,
    lambda_l1, epochs=100
)

plt.figure()
plt.plot(l1_train_losses, label="Training Cost (with L1)")
plt.plot(l1_val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("L1 Regularization: Training vs Validation Loss")
plt.legend()
plt.show()

l1_train_acc = compute_accuracy(l1_model, X_train, y_train)
l1_val_acc = compute_accuracy(l1_model, X_val, y_val)

print("L1 Training Accuracy:", l1_train_acc)
print("L1 Validation Accuracy:", l1_val_acc)

l1_weights = l1_model.linear.weight.detach().cpu().numpy().flatten()

plt.figure()
plt.hist(l1_weights, bins=30)
plt.xlabel("Weight Value")
plt.ylabel("Frequency")
plt.title("L1 Regularization Weight Distribution")
plt.show()

l1_weight_sparsity = np.sum(np.isclose(l1_weights, 0.0)) / l1_weights.size
l1_weight_magnitude = np.mean(np.abs(l1_weights))

print("L1 Weight Sparsity:", l1_weight_sparsity)
print("L1 Weight Magnitude:", l1_weight_magnitude)
print("Number of weights driven to zero:", np.sum(np.isclose(l1_weights, 0.0)))

"""L2

"""

lambda_l2 = 0.01

l2_model = LogisticModel(input_dim)
optimizer_l2 = optim.SGD(
    l2_model.parameters(),
    lr=0.01,
    weight_decay=lambda_l2
)

l2_train_losses, l2_val_losses = train_model(
    l2_model, optimizer_l2, criterion,
    X_train, y_train, X_val, y_val,
    epochs=100
)

plt.figure()
plt.plot(l2_train_losses, label="Training Loss (with L2)")
plt.plot(l2_val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("L2 Regularization: Training vs Validation Loss")
plt.legend()
plt.show()

l2_train_acc = compute_accuracy(l2_model, X_train, y_train)
l2_val_acc = compute_accuracy(l2_model, X_val, y_val)

print("L2 Training Accuracy:", l2_train_acc)
print("L2 Validation Accuracy:", l2_val_acc)

l2_weights = l2_model.linear.weight.detach().cpu().numpy().flatten()

plt.figure()
plt.hist(l2_weights, bins=30)
plt.xlabel("Weight Value")
plt.ylabel("Frequency")
plt.title("L2 Regularization Weight Distribution")
plt.show()

l2_weight_magnitude = np.mean(np.abs(l2_weights))
  l2_weight_sparsity = np.sum(np.isclose(l2_weights, 0.0)) / l2_weights.size

  print("L2 Weight Magnitude:", l2_weight_magnitude)
  print("L2 Weight Sparsity:", l2_weight_sparsity)

"""Elastic

"""

lambda_l1 = 0.005
lambda_l2 = 0.005

elastic_model = LogisticModel(input_dim)
optimizer_elastic = optim.SGD(
    elastic_model.parameters(),
    lr=0.01,
    weight_decay=lambda_l2
)

elastic_train_losses = []
elastic_val_losses = []

for epoch in range(100):
    elastic_model.train()
    optimizer_elastic.zero_grad()

    y_pred = elastic_model(X_train)
    loss = criterion(y_pred, y_train)
    cost = loss + l1_loss(elastic_model, lambda_l1)

    cost.backward()
    optimizer_elastic.step()

    elastic_model.eval()
    with torch.no_grad():
        y_val_pred = elastic_model(X_val)
        val_loss = criterion(y_val_pred, y_val)

    elastic_train_losses.append(cost.item())
    elastic_val_losses.append(val_loss.item())

plt.figure()
plt.plot(elastic_train_losses, label="Training Cost (Elastic Net)")
plt.plot(elastic_val_losses, label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Elastic Net: Training vs Validation Loss")
plt.legend()
plt.show()

elastic_train_acc = compute_accuracy(elastic_model, X_train, y_train)
elastic_val_acc = compute_accuracy(elastic_model, X_val, y_val)

print("Elastic Net Training Accuracy:", elastic_train_acc)
print("Elastic Net Validation Accuracy:", elastic_val_acc)

elastic_weights = elastic_model.linear.weight.detach().cpu().numpy().flatten()

elastic_weight_sparsity = np.sum(np.isclose(elastic_weights, 0.0)) / elastic_weights.size
elastic_weight_magnitude = np.mean(np.abs(elastic_weights))

print("Elastic Net Weight Sparsity:", elastic_weight_sparsity)
print("Elastic Net Weight Magnitude:", elastic_weight_magnitude)

results = pd.DataFrame({
    "Model": ["Baseline", "L1", "L2", "Elastic Net"],
    "Train Loss": [
        baseline_train_losses[-1],
        l1_train_losses[-1],
        l2_train_losses[-1],
        elastic_train_losses[-1]
    ],
    "Validation Loss": [
        baseline_val_losses[-1],
        l1_val_losses[-1],
        l2_val_losses[-1],
        elastic_val_losses[-1]
    ],
    "Loss Gap": [
        baseline_train_losses[-1] - baseline_val_losses[-1],
        l1_train_losses[-1] - l1_val_losses[-1],
        l2_train_losses[-1] - l2_val_losses[-1],
        elastic_train_losses[-1] - elastic_val_losses[-1]
    ],
    "Validation Accuracy": [
        baseline_val_acc,
        l1_val_acc,
        l2_val_acc,
        elastic_val_acc
    ],
    "Weight Sparsity": [
        weight_sparsity_baseline,
        l1_weight_sparsity,
        l2_weight_sparsity,
        elastic_weight_sparsity
    ],
    "Weight Magnitude": [
        weight_magnitude_baseline,
        l1_weight_magnitude,
        l2_weight_magnitude,
        elastic_weight_magnitude
    ]
})

results

