# -*- coding: utf-8 -*-
"""dl7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nzj-gRRtRSTa9lKMbc2xc7b55-PzSvWm
"""

pip install torch torchvision

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

#Dataset
transform  = transforms.ToTensor()
train_data = datasets.MNIST(root='./data', train=True,  download=True, transform=transform)
test_data  = datasets.MNIST(root='./data', train=False, download=True, transform=transform)
train_loader = DataLoader(train_data, batch_size=128, shuffle=True)
test_loader  = DataLoader(test_data,  batch_size=16,  shuffle=True)

class Encoder(nn.Module):
    def __init__(self, input_dim=784, hidden_dim=400, latent_dim=20):
        super().__init__()
        self.fc        = nn.Linear(input_dim, hidden_dim)
        self.fc_mu     = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        self.relu      = nn.ReLU()

    def forward(self, x):
        h       = self.relu(self.fc(x))
        mu      = self.fc_mu(h)
        log_var = self.fc_logvar(h)
        return mu, log_var

def reparameterize(mu, log_var):
    std = torch.exp(0.5 * log_var)
    eps = torch.randn_like(std)
    return mu + eps * std

class Decoder(nn.Module):
    def __init__(self, latent_dim=20, hidden_dim=400, output_dim=784):
        super().__init__()
        self.fc1     = nn.Linear(latent_dim, hidden_dim)
        self.fc2     = nn.Linear(hidden_dim, output_dim)
        self.relu    = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, z):
        h = self.relu(self.fc1(z))
        return self.sigmoid(self.fc2(h))

class VAE(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = Encoder()
        self.decoder = Decoder()

    def forward(self, x):
        x = x.view(-1, 784)
        mu, log_var = self.encoder(x)
        z = reparameterize(mu, log_var)
        x_recon = self.decoder(z)
        return x_recon, mu, log_var

def vae_loss(x_recon, x, mu, log_var):
    x_flat     = x.view(-1, 784)
    recon_loss = nn.functional.binary_cross_entropy(x_recon, x_flat, reduction='sum')
    kl_loss    = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())
    return recon_loss, kl_loss

device    = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model     = VAE().to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-3)

sample_imgs, sample_labels = next(iter(test_loader))
fig, axes = plt.subplots(2, 8, figsize=(14, 4))
fig.suptitle('Sample MNIST Input Images', fontsize=14, fontweight='bold')
for i in range(16):
    ax = axes[i // 8][i % 8]
    ax.imshow(sample_imgs[i].squeeze(), cmap='gray')
    ax.set_title(f'Label: {sample_labels[i].item()}', fontsize=8)
    ax.axis('off')
plt.tight_layout()
plt.savefig('1_input_images.png', dpi=120)
plt.show()
print(" Saved: 1_input_images.png")

EPOCHS = 10
recon_losses_per_epoch = []
kl_losses_per_epoch    = []

print(f"\nTraining on: {device}")
print("=" * 60)

for epoch in range(1, EPOCHS + 1):
    model.train()
    total_recon = total_kl = 0

    for x, _ in train_loader:
        x = x.to(device)
        x_recon, mu, log_var = model(x)

        recon_loss, kl_loss = vae_loss(x_recon, x, mu, log_var)
        loss = recon_loss + kl_loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_recon += recon_loss.item()
        total_kl    += kl_loss.item()

    n = len(train_loader.dataset)
    avg_recon = total_recon / n
    avg_kl    = total_kl    / n

    recon_losses_per_epoch.append(avg_recon)
    kl_losses_per_epoch.append(avg_kl)

    print(f"Epoch {epoch:02d}/{EPOCHS} | "
          f"Reconstruction Loss: {avg_recon:.4f} | "
          f"KL Divergence Loss:  {avg_kl:.4f} | "
          f"Total: {avg_recon + avg_kl:.4f}")

print("=" * 60)
print("Training complete!")

epochs_range = range(1, EPOCHS + 1)
fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle('VAE Training Loss Curves', fontsize=14, fontweight='bold')

axes[0].plot(epochs_range, recon_losses_per_epoch, 'b-o', linewidth=2, markersize=5, label='Recon Loss')
axes[0].set_title('Reconstruction Loss')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(epochs_range, kl_losses_per_epoch, 'r-o', linewidth=2, markersize=5, label='KL Loss')
axes[1].set_title('KL Divergence Loss')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

total_losses = [r + k for r, k in zip(recon_losses_per_epoch, kl_losses_per_epoch)]
axes[2].plot(epochs_range, total_losses, 'g-o', linewidth=2, markersize=5, label='Total Loss')
axes[2].plot(epochs_range, recon_losses_per_epoch, 'b--', linewidth=1.5, alpha=0.6, label='Recon')
axes[2].plot(epochs_range, kl_losses_per_epoch,    'r--', linewidth=1.5, alpha=0.6, label='KL')
axes[2].set_title('All Losses Combined')
axes[2].set_xlabel('Epoch')
axes[2].set_ylabel('Loss')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('2_loss_curves.png', dpi=120)
plt.show()
print(" Saved: 2_loss_curves.png")

model.eval()
with torch.no_grad():
    test_imgs, _ = next(iter(test_loader))
    test_imgs    = test_imgs.to(device)
    recon_imgs, _, _ = model(test_imgs)

n_show = 8
fig, axes = plt.subplots(2, n_show, figsize=(14, 4))
fig.suptitle('Original (top) vs Reconstructed (bottom)', fontsize=13, fontweight='bold')

for i in range(n_show):
    axes[0][i].imshow(test_imgs[i].cpu().squeeze(), cmap='gray')
    axes[0][i].set_title('Original', fontsize=8)
    axes[0][i].axis('off')

    axes[1][i].imshow(recon_imgs[i].cpu().view(28, 28), cmap='gray')
    axes[1][i].set_title('Recon', fontsize=8)
    axes[1][i].axis('off')

plt.tight_layout()
plt.savefig('3_reconstruction.png', dpi=120)
plt.show()
print("Saved: 3_reconstruction.png")

model.eval()
all_mu     = []
all_labels = []

with torch.no_grad():
    for x, labels in test_loader:
        x = x.to(device)
        mu, _ = model.encoder(x.view(-1, 784))
        all_mu.append(mu.cpu().numpy())
        all_labels.append(labels.numpy())

all_mu     = np.concatenate(all_mu,     axis=0)
all_labels = np.concatenate(all_labels, axis=0)

plt.figure(figsize=(9, 7))
scatter = plt.scatter(all_mu[:, 0], all_mu[:, 1],
                      c=all_labels, cmap='tab10', alpha=0.5, s=5)
plt.colorbar(scatter, label='Digit Class')
plt.title('2D Latent Space (μ dim 0 vs μ dim 1)\nColored by Digit Class',
          fontsize=13, fontweight='bold')
plt.xlabel('Latent Dimension 1 (μ₀)')
plt.ylabel('Latent Dimension 2 (μ₁)')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('5_latent_space.png', dpi=120)
plt.show()
print(" Saved: 5_latent_space.png")

