# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JyB54h6dxCP0nELuyaqjFtyJiFFFXaz
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

# 1. Prepare Data
transform = transforms.ToTensor()
train_data = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_data = datasets.FashionMNIST(root='./data', train=False, transform=transform)

train_loader = torch.utils.data.DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=64, shuffle=False)

class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.main = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 256), nn.ReLU(),
            nn.Linear(256, 128), nn.ReLU(),
            nn.Linear(128, 64),  nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.main(x)

model = SimpleNet()
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

# 3. Training Loop
for epoch in range(10):
    total_loss = 0
    for images, labels in train_loader:
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass (Learning)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} - Loss: {total_loss/len(train_loader):.4f}")

# 4. Final Accuracy Check
correct, total = 0, 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"\nTest Accuracy: {100 * correct / total:.2f}%")

import matplotlib.pyplot as plt

# Assuming you stored your losses in a list called 'epoch_losses' during training
def plot_loss(losses):
    plt.figure(figsize=(8, 5))
    plt.plot(losses, marker='o', color='b', label='Training Loss')
    plt.title('Loss Over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

# Example usage (add 'epoch_losses.append(avg_loss)' to your training loop)
# plot_loss(epoch_losses)

def visualize_preds(model, test_loader):
    model.eval()
    images, labels = next(iter(test_loader)) # Get a batch of images
    outputs = model(images)
    _, preds = torch.max(outputs, 1)

    # Fashion MNIST class names
    classes = ['T-shirt', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot']

    plt.figure(figsize=(12, 12))
    for i in range(9): # Show first 9 images
        plt.subplot(3, 3, i+1)
        plt.imshow(images[i].squeeze(), cmap='gray')
        color = 'green' if preds[i] == labels[i] else 'red'
        plt.title(f"Pred: {classes[preds[i]]}\nActual: {classes[labels[i]]}", color=color)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

# Run visualization
visualize_preds(model, test_loader)



