# -*- coding: utf-8 -*-
"""dl_lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBLDm2YVo64T5-wkowgGlbHXKP4p6a_y
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import matplotlib.pyplot as plt

transform = transforms.Compose([
    transforms.Resize((32,32)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("test.zip", 'r') as zip_ref:
    zip_ref.extractall()

import os

print(os.listdir())
print(os.listdir("test"))

dataset = datasets.ImageFolder(
    root="test",
    transform=transform
)

print("Total Images:", len(dataset))
print("Classes:", dataset.classes)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=16,
    shuffle=False
)

images, labels = next(iter(train_loader))

print("Image batch shape:", images.shape)
print("Labels:", labels)

import torch.nn as nn

class SparseAutoencoder(nn.Module):

    def __init__(self):
        super(SparseAutoencoder, self).__init__()

        self.encoder = nn.Sequential(
            nn.Linear(3072,1024),
            nn.ReLU(),
            nn.Linear(1024,512),
            nn.Sigmoid()
        )

        self.decoder = nn.Sequential(
            nn.Linear(512,1024),
            nn.ReLU(),
            nn.Linear(1024,3072),
            nn.Sigmoid()
        )

    def forward(self,x):

        encoded = self.encoder(x)
        decoded = self.decoder(encoded)

        return encoded, decoded

import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = SparseAutoencoder().to(device)

criterion = nn.MSELoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)

def sparsity_penalty(encoded, rho=0.05, beta=1):

    rho_hat = torch.mean(encoded, dim=0)

    kl = rho * torch.log(rho / rho_hat) + \
         (1 - rho) * torch.log((1 - rho) / (1 - rho_hat))

    return beta * torch.sum(kl)

epochs = 20

for epoch in range(epochs):

    model.train()
    total_loss = 0

    for images, _ in train_loader:

        images = images.view(images.size(0), -1).to(device)

        encoded, outputs = model(images)

        recon_loss = criterion(outputs, images)

        sparse_loss = sparsity_penalty(encoded)

        loss = recon_loss + sparse_loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss/len(train_loader):.4f}")

model.eval()

val_loss = 0

with torch.no_grad():

    for images, _ in val_loader:

        images = images.view(images.size(0), -1).to(device)

        _, outputs = model(images)

        loss = criterion(outputs, images)

        val_loss += loss.item()

print("Validation Loss:", val_loss/len(val_loader))

import matplotlib.pyplot as plt

dataiter = iter(val_loader)
images, _ = next(dataiter)

images_flat = images.view(images.size(0), -1).to(device)

_, outputs = model(images_flat)

images = images.view(-1,3,32,32)
outputs = outputs.view(-1,3,32,32).detach().cpu()

fig, axes = plt.subplots(2,5, figsize=(10,4))

for i in range(5):

    axes[0,i].imshow(images[i].permute(1,2,0))
    axes[0,i].set_title("Original")
    axes[0,i].axis("off")

    axes[1,i].imshow(outputs[i].permute(1,2,0))
    axes[1,i].set_title("Reconstructed")
    axes[1,i].axis("off")

plt.show()